### ISSUE TITLE
🎨  Create a Bot Choose file Input

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa#120]
#  Create a Bot Choose file Input

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want to add an image, name and description of my bots when creating them.

### Description

Currently, users are able to create new bots and add an image to it but the design is not user friendly. The Image should also only be saved when the user clicks the create button. This ensures we do not upload images incase the user cancels the creation of the bot.

The current design for this feature is as shown below:
<img width="1440" alt="Screenshot 2022-11-02 at 08 45 20" src="https://user-images.githubusercontent.com/29625264/199408137-ca33498a-09c3-4743-8bc7-6be4eb9f06ee.png">

The Modal needs to appear as shown below when an image has been uploaded:
<img width="1439" alt="Screenshot 2022-11-02 at 08 42 19" src="https://user-images.githubusercontent.com/29625264/199408214-f6b94ab3-0d7f-45d4-b9ff-daa230b96296.png">

The Modal needs to appear as shown below when no image has been uploaded:
<img width="1440" alt="Screenshot 2022-11-02 at 09 23 20" src="https://user-images.githubusercontent.com/29625264/199413752-1b848fcf-ac48-488c-8df8-f8e4c2840881.png">

The Dialog needs to appear and function as described above.

On the update dialog I can:
1. Attach an image when creating the bot
1. Add my bot name.
2. Add my bot description.

Your assignment is to redesign the modal to appear as shown, make sure the modal height is correct too to avoid overflow issues.

### Technical Analysis

This feature can be found in libs/features/convs-mgr/home/modals/create-bot-modal

For this feature you'll have to:
```markdown
1. Redesign the modal

```

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is well structured following the Technical Analysis.
4. All functions of the form work seamlessly.

**Comment by C-Ogamba** [comment]
I'll work on this issue

**Comment by CalebKabaya** [comment]
i will work on this issue
