### ISSUE TITLE
🎨 App Design: Log In Page

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa#129]
#  App Design: Log In Page
---

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want to Log In to the application with my credentials or use a google log In.

### Description

The current Log In page is as shown below:
![Screenshot 2022-11-08 at 11 58 11](https://user-images.githubusercontent.com/29625264/200525359-b3588411-1093-4058-94c0-4b1befca9174.png)

The page needs to be updated to appear as shown below:

<img width="1437" alt="Screenshot 2022-11-08 at 12 19 04" src="https://user-images.githubusercontent.com/29625264/200525415-140f7427-f777-43dc-b480-4e3b4d15aaf2.png">

Your assignment is to redesign the page to appear as above.
When a user clicks on the "Log In" Button, the text should change to "Please wait..." with a material spinner next to it. The text fields on the page should also be disabled when logging in the user.

### Technical Analysis

This feature can be found in libs/features/app/auth/login. 

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.

**Comment by Developer-Gitonga** [comment]
Working on the issue.
