### ISSUE TITLE
🤖 🎨 [Design] Design of the block base layout

### ISSUE THREAD

**Issue by jrosseel** [italanta/elewa#13]
## Overview

For consistency, we wish a base design template for each of the blocks. This base design is managed from the BlockComponent, from which all other blocks are loaded.

<img width="806" alt="image" src="https://user-images.githubusercontent.com/3729474/181260522-09bf42be-dc0c-453b-862b-f9fb5435cf90.png">

### Technical analysis

- Update all the changes in the convl-block component (features/convs-mgr/stories/blocks/library/main -> components/block)

- Add blockTitle and blockIcon (type string) to the StoryBlock model

**Comment by IanKoech** [comment]
I will work on this issue

**Comment by pmutua** [comment]
@trevin-livele will work on this

**Comment by jrosseel** [comment]
Closed as resolved
