### ISSUE TITLE
🎨  App Design: Sign up Page

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa#130]
#  App Design: Sign up Page
---

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want to Sign up to use the application with my credentials or use a google sign up.

### Description

The current sign up page is as shown below:
![Screenshot 2022-11-08 at 12 33 32](https://user-images.githubusercontent.com/29625264/200528653-c5141955-d07b-4b8a-a954-5c11799d3a84.png)

The page needs to be updated to appear as shown below:
<img width="1437" alt="Screenshot 2022-11-08 at 12 32 44" src="https://user-images.githubusercontent.com/29625264/200528696-58d7ed55-0a1d-4c60-86e1-8a9f47932bc5.png">

Your assignment is to redesign the page to appear as above.

When a user clicks on the "Create Account" Button, the text should change to "Please wait..." with a material spinner next to it. The text fields on the page should also be disabled when saving the user.
### Technical Analysis

This feature can be found in libs/features/app/auth/register. 

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.

**Comment by lilmithi** [comment]
Working on this

**Comment by JamesMGithire** [comment]
Working on this

**Comment by NewtonOmbese** [comment]
Working on this
