### ISSUE TITLE
🤖 [Feature] Delete a block 

### ISSUE THREAD

**Issue by jrosseel** [italanta/elewa#14]
**Depends on #13 !**

### Summary

When a user clicks delete on the side menu of a block, the block needs to be deleted from the editor.

### Acceptance criteria

- Upon saving and reloading, the block needs to be removed

**Comment by CarolGitonga** [comment]
I can work on this issue

**Comment by pmutua** [comment]
> I can work on this issue

✅ OK you can start on this

**Comment by maureenndiema** [comment]
interested
