### ISSUE TITLE
🎨 Blocks List Layout

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa#141]
#   Blocks List Layout
---

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want to view a list of all available blocks.

### Description

The blocks list is as shown below:

<img width="1433" alt="Screenshot 2022-11-22 at 12 11 27" src="https://user-images.githubusercontent.com/29625264/203273945-b571f858-d11a-4952-9f7c-174b90d16dd8.png">

The component needs to be updated to appear as shown below:

<img width="1440" alt="Screenshot 2022-11-22 at 12 12 31" src="https://user-images.githubusercontent.com/29625264/203273984-ae62a9c0-d168-49d2-9222-ef4c996b1111.png">

Your assignment is to redesign the component to appear as above.
When a user hovers over a block the background color changed to the primary purple and the text and icon to white, a slight box shadow should also be applied to convey an elevation effect.

Take note of the different blocks categories.

### Technical Analysis

This feature can be found in libs/features/convs-mgr/stories/editor/blocks-library.

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. All the functionality still works i.e search and clicks.

**Comment by indomitable-core** [comment]
I am working on this issue @IanOdhiambo9
