### ISSUE TITLE
🗺️  Semi-Collapsible SideNav

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa#142]
#  Semi-Collapsible SideNav
---

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want to view the side navigation

### Description

The current sidenav collapses completely when a user clicks on the menu icon, this behaviour should change and instead minimize the sidenav to only shoe the nav icons as shown below:

When sidenav is fully active (show text and icons) To be left as is (do not edit):

<img width="1440" alt="Screenshot 2022-11-22 at 12 23 30" src="https://user-images.githubusercontent.com/29625264/203276797-aad589cd-6c26-4f8a-9d55-05fd9a156f61.png">

When sidenav is collapsed (show only icons):

<img width="1440" alt="Screenshot 2022-11-22 at 12 24 19" src="https://user-images.githubusercontent.com/29625264/203276827-a25bb0ef-0cae-4b7f-9640-da6b91bf7084.png">

Your assignment is to redesign the component to appear as above.

Please take note of the sidenav icons 

### Technical Analysis

This feature can be found in libs/elements/layout/page-convl

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. All the functionality still works i.e clicks and nav.

**Comment by Developer-Gitonga** [comment]
Almost done
