### ISSUE TITLE
🤖 [Feature] Copy a block

### ISSUE THREAD

**Issue by jrosseel** [italanta/elewa#15]
**Depends on #13 !**

### Summary

When a user clicks copy on the side menu of a block, a new block needs to be spawned on the editor with exactly the same fields as the originating block

### Technical analysis

Use deepClone of lodash to copy the block data, to avoid the two block pointers pointing to the same adress

### Acceptance criteria

- Upon saving and reloading, the new block is there with its own configuration

**Comment by pmutua** [comment]
> I will work on this

✅ OK

**Comment by ReaganCn** [comment]
Closed by pr #271
