### ISSUE TITLE
🧱 📹  Video Block - Output

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa#154]
#  Video Block - Output
---

#### Note this issue is dependent on #143, please complete that one first.

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a block I can use to send video (mp4) to my users.

### Description

The video block is used to send a simple video files to the user, it has the following features:

```
1. A header (Inherited from the block component)
2. An input field that contains the link to the video (online url) - Use AngularFireStorage to save file on Storage
3. An input field that contains a caption
```

Currently the video block is as shown below:

<img width="465" alt="Screenshot 2022-11-23 at 12 05 17" src="https://user-images.githubusercontent.com/29625264/203507702-06f88cb8-67d5-4bc0-b19c-04458ccee880.png">

We need it to be updated to appear as shown below:

<img width="457" alt="Screenshot 2022-11-23 at 12 04 43" src="https://user-images.githubusercontent.com/29625264/203507720-0a7c4148-8b04-4e6e-8749-1850a12e5132.png">

Your assignment is to redesign the component to appear as above.

Please take note of all the design features

### Technical Analysis

This feature can be found in libs/features/stories/blocks/library

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. All the functionality still works i.e copy, delete, upload video and rendering of the block.

**Comment by indomitable-core** [comment]
I am working on this issue
