### ISSUE TITLE
environment file

### ISSUE THREAD

**Issue by suzuya1331** [italanta/elewa#163]
i wanted to try to build the repo on my local machine , but i found the environment file.
is there a change to get template of the environment files?
![image](https://user-images.githubusercontent.com/60817875/204494623-c4bbe9b7-4b23-46c7-9513-2e84bf480e26.png)

**Comment by Nyash-Mauro** [comment]
Slack me MAurice Nyanja kindly

**Comment by Nyash-Mauro** [comment]
And close this here kindly

**Comment by suzuya1331** [comment]
i don't have slack , can you send me message on this email
***@***.***
Thank you
