### ISSUE TITLE
🎨 ⚡ [Feature] Add a filter to the bot list component

### ISSUE THREAD

**Issue by jrosseel** [italanta/elewa#21]
## Filtering bots

**NOTE: This feature depends on implementation of #20 !** Please complete that issue first.

When a user logs in, they are sent to the bot builder homepage. Here they can view all the bots they are building and go to their builder. 

To manage many bots, it would be handy to have a filter functionality here.

---

Quick links: [Summary](#summary) | [Description](#description) | [Template](#template) | [Example](#example) | [Resources](#resources)

---

### Summary

As a user, I want to search my bots on name so that I can manage large number of bots.

### Description

Please finish implementation of #20 first and only then do this task.
A filter field needs to be added to the component using following template:

<img width="984" alt="image" src="https://user-images.githubusercontent.com/3729474/182602931-f04253fa-cb36-471f-a9b4-a7d794572801.png">

When I type in a character or series of characters, only bots which names' match the characters should be shown.

### Technical analysis

This feature requires us to dive into the state layer. We're going to use component-level state for this feature.

On our story-list component:
```markdown
1. Add a small form which holds a mat-form-field and mat-input of type text. Use reactive forms only! - [Reference](https://angular.io/guide/reactive-forms).
2. **OnInit**, wire together the reactive form field and the _stories$$ using an rxjs "combineLatest".
3.  Map the values of the result (= has to be a filtered list based on the search field!) to your stories$ observable, becoming local state.
```

### Acceptance criteria

1. Needs to meet design spec
2. State needs to be properly implemented

**Comment by DynastyElvis** [comment]
i intend to work on this issue

**Comment by jrosseel** [comment]
Closed as resolved
