### ISSUE TITLE
🎨 As a user I should be able to add block that can post data to a URL endpoint

### ISSUE THREAD

**Issue by ReaganCn** [italanta/elewa#225]
## User stories

Implement the UI of a `Webhook Block` whose function is to post data to a URL endpoint. This issue depends on issue #157. So you can start with that.

The block should have a request section with the below inputs:
- A text input to select the method and the post url - saved as string - *required field
<img width="467" alt="image" src="https://user-images.githubusercontent.com/34684844/209349309-dc1d341f-deb8-461d-9576-d42dc1ac3f10.png">

- A multi-select dropdown which will be populated with the variables defined in input blocks upto that point - *optional field
- Authorization token - *optional field

*For simplicity, the http method drop can be outside the textbox for now.
*The http methods include: POST, GET, DELETE

The Webhoook interface can have the below structure: 
```
{

/** The http method. Should be a drop down */
htttpMethod: HttpMethodTypes;

/** The http url of the endpoint */
httpUrl: string;

/** An array of variables defined in the previous input blocks e.g. variable for a name input block can be `name`*/
variablesToPost: string[];

/** Optional token if required by the api we are posting to. Should be encoded with `__ENCODE_AES`*/
authorizationToken?: string;

}
```

---

***Also note that:***

The input blocks when added should save that variable to a variable document in `story/{storyId}/config/variables`. All the properties are variables added by the user.

This means you should have a `Variables Store` that updates, retrieves and deletes variables.

**Comment by indomitable-core** [comment]
I am working on this issue
