### ISSUE TITLE
🎨 Style story-editor connectors.

### ISSUE THREAD

**Issue by jrosseel** [italanta/elewa#23]
## Styling story-editor connectors

Implement the connectors and endpoints design spec on the StoryEditor.

## Description
Block endpoints and connectors should look like this:

<img width="487" alt="image" src="https://user-images.githubusercontent.com/3729474/182616677-70cc5601-eaaf-469a-bdcf-07994d4ca1e8.png">

### Technical Description 

The connectors and endpoints **do not live in Angular but live in JsPlumb**. They are drawn on top of the Angular components. Therefore, we need to refer to the JsPlumb documentation and decorate the connectors with classes which can be configured from CSS.

Refer to the following documentation:

- Using the FlowChart connector

https://docs.jsplumbtoolkit.com/community-2.x/current/articles/connectors.html 

- Styling of JsPlumb using CSS
 
https://docs.jsplumbtoolkit.com/community/lib/connectivity
https://docs.jsplumbtoolkit.com/community/lib/endpoints

**Comment by OGENDI** [comment]
I'll work on this issue

**Comment by LemmyMwaura** [comment]
If this is still up for grabs, I wouldn't mind working on it.

**Comment by jrosseel** [comment]
Closed as resolved
