### ISSUE TITLE
🎨 🧱  Improvements on delete block

### ISSUE THREAD

**Issue by ReaganCn** [italanta/elewa#241]
## User stories

Currently the delete bock works but we need a few enhancements to improve user experience.

---

Quick links: [Description](#description) | [Template](#template) | [Example](#example) | [Resources](#resources)

---

### Improvement - More like a bug

Currently when a block is deleted, the connection to that block still exists on the database. So this can cause issues when the bot is trying to play through the blocks and hits a connection which does not lead to anywhere.

The connections linked to the block should also be deleted when the block is deleted

### Acceptance Criteria

1. Once I click on delete block icon, the block should dissapper from view. 
1. Once a block is deleted the connections to and from the block should me marked as deleted.

**Comment by ReaganCn** [comment]
Improvement 2, is already described on issue #30

**Comment by jobkarani** [comment]
We are working on this with @DMacharia

**Comment by ReaganCn** [comment]
Updated description

**Comment by ReaganCn** [comment]
> We are working on this with @DMacharia

I have updated the description
