### ISSUE TITLE
🎨 [Application Design] Create a new Bot dialog

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa#25]
#  Create a new Bot dialog

When a user logs in, they are navigated to the application homepage (Dashboard). Here they can view an analysis of all their bots and all the bots they are building and go to their builder.

---

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I need an interface that provides a button which enables me to create a new bot in my bots section by providing a name and a description.

### Description

Please finish #24 first before attempting this.

The button need to appear as shown in this design:

<img width="1158" alt="Screenshot 2022-08-03 at 17 35 15" src="https://user-images.githubusercontent.com/29625264/182635896-19a7cdf2-8462-4e99-b88e-bde93f727fe5.png">

The create new bot modal needs to appear as shown in this design:

<img width="1440" alt="Screenshot 2022-08-03 at 18 03 46" src="https://user-images.githubusercontent.com/29625264/182642810-155ec61f-93c3-44c2-a7c6-96986b964512.png">

Clicking the button opens the dialog above.

On this dialog I can :
1. Enter the name of my new bot.
2. Enter the description of my new bot.
3. Click cancel to abort the journey by closing the dialog.

Your assignment is to create a button that opens the modal and a modal that contains the name and description fields.

### Technical Analysis

You're adding this feature in libs/features/convs-mgr/home. Currently the functionality is split across the home page and the story-list-item component.

For this feature you'll have to:
```markdown

1. Create the button in the home-page of the lib above.
2. Create a modals folder in libs/features/convs-mgr/home/src/lib.
3. Generate a create-bot-modal component in the modals folder.
4. Edit the component by including the input fields and buttons.
5. Create an openDialog function in the home-page that opens the dialog.
```

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is well structured following the Technical Analysis.

**Comment by meshack34** [comment]
I will work on this issue

**Comment by Daniel-darnell** [comment]
I would like to work on this issue

**Comment by jrosseel** [comment]
Closed as completed
