### ISSUE TITLE
🐛 📹 When uploading a video its takes time but it saves.

### ISSUE THREAD

**Issue by ReaganCn** [italanta/elewa#252]
**Describe the bug**

When uploading a video its takes time but it saves. Even on small video files.

We should also have a spinner/progress bar on the video block that indicates the status of the upload.

**To Reproduce**
1. Run the Elewa CLM application
2. Create a new story and add a video block
3. Click on the 'play' icon on the block
4. Select a video file to upload

**Expected behavior**
Small video files shoudl not take time, and also  we should also have a spinner/progress bar on the video block that indicates the status of the upload.

**Comment by order6677** [comment]
am doing this
