### ISSUE TITLE
🤖 ♻️ Handle media files and save messages at the message parser level.

### ISSUE THREAD

**Issue by ReaganCn** [italanta/elewa#255]
## Description

Arising from PR #210 

Processing files should be done at Message parser level. You can have subtypes of MessageParser which is fileMessage, which does this

Then FileMessage is next inherited by the specific file types i.e. AudioMessage, ...

So save method in this subclass does
{
 fileMessage.url = ...
 return super.save(fileMessage, endUserId)
}

_Originally posted by @jrosseel in https://github.com/italanta/elewa/pull/210#discussion_r1054142415_

**Comment by kw2s** [comment]
On it
