### ISSUE TITLE
🎨 [Application Design] Create Block components list

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa#27]
#  Create the Block components list

When a user navigates to the bot builder page, they can view a list of block components they can use to build their bot on the bot builder viewport. 

---

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a menu that contains the different bot block components I can use to build my bot.

### Description

Please finish #24 first before attempting this.

The bot builder page block components list appears as shown below currently:

<img width="1440" alt="Screenshot 2022-08-03 at 20 54 28" src="https://user-images.githubusercontent.com/29625264/182676529-72ab1d35-97c6-4054-a551-1e991593ef20.png">

The page does not contain an interface for selecting different types of bot block components that can be used to build the bots. The page has been improved to accommodate this features as shown below:

<img width="1440" alt="Screenshot 2022-08-03 at 20 48 18" src="https://user-images.githubusercontent.com/29625264/182676264-cee58000-1596-480d-9013-2d880022afe9.png">

The menu list needs to appear as shown in the design above.

On the block menu list I can:
1. View a list of block components.
2. Select a block component by clicking on it.
3. Filter the list using a search-box to quickly find a block (Leave this out as it's implemented in another feature).

Your assignment is to create the block menu list with the buttons for all the block elements.

### Technical Analysis

This feature can be found in libs/features/convs-mgr/stories/blocks/library/main. 

For this feature you'll have to:
```markdown

1. Generate the block components in the components folder of the library above.
2. Create the interfaces for the block components in (@app/model/convs-mgr/stories/blocks/messaging).

```

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
4. The component is well structured following the Technical Analysis.

**Comment by meshack34** [comment]
I will work on this
