### ISSUE TITLE
🎨 💾  As a user I should be allowed to set variables on input blocks

### ISSUE THREAD

**Issue by ReaganCn** [italanta/elewa#298]
## User stories

As a user I should be allowed to set variables on input blocks.  I need to be able to set the variable's name and data type (such as string or number) so that I can save user input to that variable in the chatbot flow. This will enable me to create personalized and dynamic responses for users based on their input.

---

Quick links: [Summary](#summary) | [Description](#description) | [Template](#template) | [Example](#example) | [Resources](#resources)

---

### Summary

As a user I should be allowed to set variables on input blocks.  I need to be able to set the variable's name and data type (such as string or number) so that I can save user input to that variable in the chatbot flow. This will enable me to create personalized and dynamic responses for users based on their input.

### Description

The same as variables used in programming, the following rules should be asserted:

1. Names can contain letters, digits, underscores, and dollar signs.
2. Names must begin with a letter.
3. Names must not contain whitespace
4. Names are case sensitive (y and Y are different variables).
5. Reserved words (like userId and phoneNumber) cannot be used as names.

In addition, we will have default system-wide variables regardless of the story i.e. `userId, phoneNumber and storyId`, and these can be set when an org registers for an account. 

There should be an input field that a user can set the block variable name and a drop down for supported variable types:
```
export enum VariableTypes {
  String                    = 1,
  Number                    = 2,
  Array                     = 3,
  ArrayWithTypeAndValue     = 4
}
```

### Acceptance Criteria

1. A clean UI that makes it easy to set and update variables and changes reflected in the DB
2. There should be a description informing the user how to use these variables in stories and limitations e.g. shouldn't use a variable before its value is set in the flow
3. Variable names are validated and appropriate error messages shown below the variable field.

Please also note:

1. Blocks such as name, email and phone, already have their variables set to their names, however the variable field should be pre populated and allow the user to edit
2. The webhook block has two sets of variables 'variablesToPost' and 'variablesToSave'. This block alone should be handled in a separate PR

**Comment by jobkarani** [comment]
I am working on this.
