### ISSUE TITLE
🗃️ [Connections State] Remove deleted connections

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa#30]
#  Remove deleted connections from the database
#### NOTE: This feature depends on #29, ensure you understand how the state is handled there first.

When a user navigates to the bot builder page, they can view a list of block components they can use to build their bot on the bot builder viewport. 

---

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want to be able to permanently delete connections connecting my blocks.

### Description

The connections information are stored in a story sub-collection [connections], please refer to the StoryBlocksConnections store in state. Every time a new connection is created/updated the data is saved as a document in the collection above. The important information the document contains are : 
```markdown

1. id(connection-id).
2. sourceId(identifies option where the connection is from).
3. targetId(identifies the block where the connection is linked to).

 ```

Your assignment is to check for all the deleted connections when saving the story and make sure they are removed from the connections collection.

### Technical Analysis

This feature can be found in : 

- libs/features/convs-mgr/stories/editor/model
- libs/state/convs-mgr/stories/block-connections

For this feature you'll have to:
```markdown

1. Understand the state layer of the editor frame.
2. Implement a function that determines which connections were deleted.
3. Use the story connections store to remove the documents from the database.

```

### Acceptance Criteria

1. When rendered the deleted connections are not present in the view.

**Comment by ReaganCn** [comment]
Closed by PR #312
