### ISSUE TITLE
🐛 Media/File upload blocks disappear if not saved immediately

### ISSUE THREAD

**Issue by njoroge-jane** [italanta/elewa#303]
**Describe the bug**
Blocks that require an attachment ( i.e document and video blocks ) disappear if not saved immediately after adding the attachment which is similar to issue #301   

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Document block' or 'Video block'
2. Click on on them
3. Add an attachment either video or document
4. See bug

**Expected behaviour**
After adding an attachment the block should not disappear and allow the user to continue building the bot and save at their own convenience.

**Additional context**
Test both attachments before creating a pull request.

**Comment by 23po** [comment]
Working on this

**Comment by Michael-Otieno** [comment]
Working on this

**Comment by LemmyMwaura** [comment]
Solved.
