### ISSUE TITLE
🎨 📝  Add validation for text fields on blocks

### ISSUE THREAD

**Issue by njoroge-jane** [italanta/elewa#305]
## User stories

This issue depends on #316 

As a user I would like to see a warning text to notify me that there are empty text field when I try to save my progress so that I will not be able to save my progress with empty text fields.

---

Quick links: [Summary](#summary) | [Description](#description) | [Template](#template) | [Example](#example) | [Resources](#resources)

---

### Description

```markdown
1. Have a check for empty fields.
2. On click of save have a pop up on detection of empty fields. 
3. The pop up should say 'Empty text field detected'.
4. Disable save button until all text fields are filled.
```
**NOTE**: This PR has a very limited description on designs intentionally as it requires some creative input.

**Comment by Michael-Otieno** [comment]
working on this

**Comment by Michael-Otieno** [comment]
Working on this
