### ISSUE TITLE
🎨 ✏️  As a user I should be able to scroll the block list section and view more blocks

### ISSUE THREAD

**Issue by ReaganCn** [italanta/elewa#306]
## User stories

As a user I should be able to scroll the block list section and view more blocks

---

Quick links: [Summary](#summary) | [Description](#description) | [Template](#template) | [Example](#example) | [Resources](#resources)

---

### Summary

As a user of the app, I want to be able to access my block list easily and efficiently, regardless of how many entries it contains. Currently, when my block list grows in size, I am not able to access blocks at the bottom.

To improve my experience, I would like the block list menu to be scrollable vertically. This would allow me to easily navigate through my list, no matter how many items it contains.  Additionally, I would like the scrollbar to be clearly visible and easy to use. It should be large enough to easily click. This will improve my overall experience with the app and make it more user-friendly.

### Screenshot

Currently we are not able to scroll and view blocks at the bottom:
<img width="358" alt="image" src="https://user-images.githubusercontent.com/34684844/219296634-e7245748-0cb9-4c30-95fc-cf021af18d91.png">

### Acceptance Criteria

1. I should be able to view all the blocks when I scroll.
2. The scroll bar should only be visible when a mouse hovers over the block list menu.
3. The scroll bar implementation should be clean and blend with the theme colors.

**Comment by jobkarani** [comment]
I'm working on this.
