### ISSUE TITLE
🎨 📜 Make the story editor workspace endless on scroll to the right and bottom

### ISSUE THREAD

**Issue by ReaganCn** [italanta/elewa#307]
## User stories

As a user I should be able to scroll on the editor frame endlessly to the right and towards the bottom. Currently am able to scroll to the right/bottom only when I add a block to that side. I should be able to do this whether there is a block or not.

---

Quick links: [Summary](#summary) | [Description](#description) | [Template](#template) | [Example](#example) | [Resources](#resources)

---

### Screenshot

Example:
When scrolling to the right, am only able to scroll as far as the "Great. Nice to finally meet you {{name}} 😃" Message Block
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/34684844/219303672-f9a0623a-cb11-4ae3-82fb-6a2df0baba51.png">

I should be able to create extra space when I scroll regardless of whethere there is a block there or not.

### Acceptance Criteria

1. I should be able to create extra space when I scroll regardless of whethere there is a block to that side or not.
2. Record a short video/gif to show how your implentation works.

Please also note:

1. Once this is implemented, you can remove the story editor scroll bar as it conflicts with the main page scroll bar

**Comment by jobkarani** [comment]
I'm working on this.

**Comment by njoroge-jane** [comment]
This task has been reopened because the previous solution introduced some bugs therefore this task needs to be reworked on.

**Comment by Dcolonel6** [comment]
@njoroge-jane what bugs were introduced?
