### ISSUE TITLE
🎨 🤏 Add pinch to zoom functionality to story editor 

### ISSUE THREAD

**Issue by ReaganCn** [italanta/elewa#308]
## User stories

As a user, I want to be able to use pinch to zoom functionality using my mouse to easily adjust the size of my blocks. Currently, the only way to zoom in or out is by using the plus and minus buttons, which can be cumbersome and time-consuming.

---

Quick links: [Summary](#summary) | [Description](#description) | [Template](#template) | [Example](#example) | [Resources](#resources)

---

### Summary

As a user, I want to be able to use pinch to zoom functionality using my mouse to easily adjust the size of my blocks. Currently, the only way to zoom in or out is by using the plus and minus buttons, which can be cumbersome and time-consuming.

To improve my experience, I would like the story editor to support pinch to zoom functionality which should be easy to use and intuitive. It should work smoothly and without lag, allowing me to easily and accurately zoom in or out as needed. 

By having the ability to use pinch to zoom in the story editor, I will be able to create more visually appealing and readable stories. This will improve my overall experience with the app and make it more user-friendly.

### Screenshot

Currently we are using plus and minus buttons to zoom in and out.
<img width="1254" alt="image" src="https://user-images.githubusercontent.com/34684844/219306225-6921813f-e772-4ff5-846b-7f1761560a0b.png">

Use the below mouse gestures:

**Pinch** to zoom out and **Unpinch** to zoom in 

![what-is-pinch-to-zoom](https://user-images.githubusercontent.com/34684844/220285470-c08de086-0fbd-4c78-9e72-32b7ca367523.png)

### Acceptance Criteria

1. Pinch to zoom in and out should be smooth and without lag.
2. I should be able to zoom into a specific section in the editor or a block accurately.
3. The already existing buttons of zooming in and out should still be there and the zoom percentage should also reflect changes when I pinch to zoom.

**Comment by lilmithi** [comment]
Working on this

**Comment by lilmithi** [comment]
Working on this
