### ISSUE TITLE
♻️ 🎨 Move the message (text area) field of blocks to a separate component for reuse

### ISSUE THREAD

**Issue by ReaganCn** [italanta/elewa#316]
## User stories

This is a refactor, and requires the messages of story blocks to be moved to a separate component. This will ensure reusability and easy maintainability.

---

Quick links: [Summary](#summary) | [Description](#description) | [Template](#template) | [Example](#example) | [Resources](#resources)

---

### Description

This separate component for now will only have the `textarea` html element as implemented in the blocks that have a message. 

Example:
The `MessageBlockComponent` has this for its message field: `<textarea id="message" name="message" formControlName="message" type="text" rows="3"></textarea>`. This should be moved to the `TextMessageComponent` and replace the text area tag with the new component tag.

Therefore you will need to create a `TextMessageComponent` on this path: `libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/text-message-block`. 

Once that is done, replace all message fields with the new component tag, and take note of the inputs passed.

### Acceptance Criteria

1. There should be one reusabe component for text message fields.
2. The input bindings should applied down to the child `textarea` tag as before
3. The application and the styling should work exactly as before.

**Comment by DMacharia** [comment]
I am working on this
