### ISSUE TITLE
🎨 🗺️ 🖊️  Semi-Collapse Sidenav When Portal Is Open

### ISSUE THREAD

**Issue by LemmyMwaura** [italanta/elewa#320]
# Collapsible Side Nav When Portal Is Open

## User stories

As a user, I should have enough room to edit my block details. When the portal is open (when a block is selected for editing) the main Sidenav should automatically close. To achieve this we'll need to emit an event when the edit icon is clicked on a block that automatically minimises the side nav and only shows the side nav icons. 

---

Quick links: [Summary](#summary) | [Description](#description) | [Template](#template) | [Example](#example) | [Resources](#resources)

---

### Summary

As a user, I should have enough room to edit my block details.

### Description

At the moment there is not enough room to edit some of the blocks, to add enough room we've decided that the side nav should automatically close/minimise to just the icons when the portal is open (when a block is selected for editing). To achieve this we'll need to emit an event when the edit icon is clicked on a block that automatically minimises the side nav and only shows the side nav icons. 

The main block component with the edit icon can be found here: `libs\features\convs-mgr\stories\blocks\library\main\src\lib\components`

The side nav can be found here: `libs\elements\layout\page\src\lib\components\sidenav-container`

The current behaviour when the portal is open
![Side-Nav-Now](https://user-images.githubusercontent.com/20738858/220631973-59e5433f-ed1c-4c44-b1cb-0e088881471d.png)

The expected behaviour when the portal is open
![Side-Nav-Close](https://user-images.githubusercontent.com/20738858/220632014-3967e8cf-fa2e-48a6-a177-a0f350f30288.png)

### Acceptance Criteria

1. The side nav automatically minimizes to just the icons when a block is selected for editing.

**Comment by lilmithi** [comment]
Working on this
