### ISSUE TITLE
🎨 🐛 Save button is not working consistently

### ISSUE THREAD

**Issue by ReaganCn** [italanta/elewa#329]
**Describe the bug**
The save button sometimes does not work after creating a story and adding blocks. 

After further investigation we have realised that this occurs when you switch stories. See the below steps to reproduce.

**To Reproduce**
1. Once you login to the story editor, immediately create a new story, add a few blocks and save. This will save without any issues as long you have not opened any other story prior to this. If you did, refresh the browser and redo this step.
2. Now go back to the dashboard and create a new story.
3. Add a few blocks and connect them
4. Save.
5. It does not save, keeps spinning. If you refresh the page and add blocks again, it will save 🤦🏽‍♂️.

**Expected behavior**
The save button should be able to work consistently, whether am switching stories or creating a new story. It should be able to save my progress

**Comment by lilmithi** [comment]
Working on this

**Comment by lilmithi** [comment]
Working on this
