### ISSUE TITLE
🎨 ❌  As a user I should get an error prompt when I upload a wrong file format for media files

### ISSUE THREAD

**Issue by ReaganCn** [italanta/elewa#330]
## User stories

When we upload a wrong file to either the image, video or document block we don't get a message saying we uploaded the wrong kind of file.

---

Quick links: [Summary](#summary) | [Description](#description) | [Template](#template) | [Example](#example) | [Resources](#resources)

---

### Summary

When we upload a wrong file to either the image, video or document block we don't get a message saying we uploaded the wrong kind of file. 

### Description

For this, we will need a dialog box that is displayed when a user uploaded an unsupported media file. 

The modal should be created under `libs/elements/layout/modals`

**Comment by 23po** [comment]
@ReaganCn is the dialog box ready

**Comment by 23po** [comment]
working on this

**Comment by LemmyMwaura** [comment]
Completed in PR #412
