### ISSUE TITLE
🎨 🖌️  As a user I should be able to use a text editor to format my text

### ISSUE THREAD

**Issue by ReaganCn** [italanta/elewa#331]
## User stories

Depends on issue #316 

As a user of the bot creation platform, I want to be able to format my text in a text block using text editing tools, such as a WYSIWYG editor, so that I can create well-formatted and visually appealing messages for my chatbot users.
---

Quick links: [Summary](#summary) | [Description](#description) | [Template](#template) | [Example](#example) | [Resources](#resources)

---

### Description

When I am creating or editing a text block for a chatbot message, I should see a text editing toolbar that includes the below tools: 
- Bold, Italic, Underline
- Various header sizes and Paragraph mode
- Hyperlink
- Number list
- Bulleted list
- Undo and Redo Buttons

<img width="637" alt="image" src="https://user-images.githubusercontent.com/34684844/221559743-a202981a-a055-4711-a840-948c1a323daf.png">

Please remove formatting options, not mentioned above.

To achieve the above, you will need to use the [ckeditor](https://ckeditor.com/docs/ckeditor5/latest/installation/frameworks/angular.html#quick-start) library and only implement the [classic editor](https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html).

When I click on the edit button of a block containing the text message, I should be able to get this on the modal that opens: 

<img width="123" alt="image" src="https://user-images.githubusercontent.com/34684844/221556463-ca520a7c-3e9f-481a-8226-756614d11749.png">

The block itself will not have the editor.

In case the space is not enough I should be able to get a **more(three dots) button** to access more formatting options.

### Acceptance Criteria

1. I should be able to format text fully using the provided tools.
2. I should still be able to save my changes to the db, when I click the save button.

Also note that: 
The editor should be applied to the `TextMessageComponent`

### Resources:

* Setting up ckeditor in angular: [Ckeditor Quickstart](https://ckeditor.com/docs/ckeditor5/latest/installation/frameworks/angular.html#quick-start)

**Comment by Kangonga** [comment]
working on this

**Comment by lilmithi** [comment]
Working on this
