### ISSUE TITLE
🐛 Update Active Bot image

### ISSUE THREAD

**Issue by njoroge-jane** [italanta/elewa#334]
**Describe the bug**
On the active bots dashboard, there is an option to edit the bot details including the bot image. Currently on first upload the image is uploaded successfully but after the first upload there is a problem with uploading a new bot image.

**To Reproduce**
1. Go to 'Active Bots Dashboard'
2. Click on 'The menu of the bot'
3. Click on 'Edit bot'
4. Try uploading a different image from the first.
5. See errors

**Expected behavior**
On editing of the bot a new image should be uploaded seamlessly and display on the active bot.

**Screenshots**
<img width="665" alt="Screenshot 2023-03-01 at 13 00 24" src="https://user-images.githubusercontent.com/91135600/222106751-0456779a-c9d6-4de4-b965-cabb5af67874.png">

**Additional context**
The image above is provided to assist in navigating to the bug

**Comment by adamswonder** [comment]
Working on this

**Comment by Beulah-Matt** [comment]
Working on this

**Comment by adamswonder** [comment]
Working on this
