### ISSUE TITLE
🎨 💄 Redesign All Blocks

### ISSUE THREAD

**Issue by njoroge-jane** [italanta/elewa#335]
## User stories

As a user I should be able to view the new designs of the bot as per the images provided.

---

**Screenshots**
<img width="958" alt="Screenshot 2023-03-01 at 14 36 06" src="https://user-images.githubusercontent.com/91135600/222132973-467902db-b81a-43d3-b262-4054589c71dc.png">

<img width="719" alt="Screenshot 2023-03-01 at 15 07 56" src="https://user-images.githubusercontent.com/91135600/222135271-4b424308-3aeb-4203-89ab-250aadbe946f.png">

### Acceptance Criteria

1. All spaces around the bot should be exactly as demonstrated on the designs.
2. The icons should exactly match the ones on the designs provided above.(Use fontAwesome icons).
3. The implemented designs should be **pixel perfect** - important!

Please also note:

1. If a conversation about the issue I’m working on is happening,
the outcomes should be documented within that issue (not in the comments).

```

**Comment by lilmithi** [comment]
Working on this

**Comment by lilmithi** [comment]
Working on this

**Comment by lilmithi** [comment]
Doing this

**Comment by Allan-Ngugi** [comment]
Working on this.

**Comment by IanOdhiambo9** [comment]
The UI design needs to be updated first, this will revert the blocks back to a use case that does not fit the requirements at the moment.
