### ISSUE TITLE
🗒️ Video Block Modal

### ISSUE THREAD

**Issue by njoroge-jane** [italanta/elewa#336]
## User stories

As a user I would like to see a modal similar to the one below when I attempt to attach a video so that I can be able to choose the size of the video I would like to upload.

---

Quick links: [Summary](#summary) | [Description](#description) | [Template](#template) | [Example](#example) | [Resources](#resources)

---

### Description
Currently how the video block works, is once the play icon is clicked it opens the file explorer to allow  the upload the video file.

In this feature instead of opening the file explorer on click, a modal with the design below should be implemented and open the file explorer when the thumbnail space is clicked.

```markdown
1. Navigate to the video block
1. I click on the play icon.
1. A modal window should appear
1. The modal window contains the following:
  1. [A title]
  2. [Two input fields: One a name input and Second a video input]
  3. [Radio button options with the size options for the video **Note** : One should be able to select only one option]
1. A button that applies the picked option, the video file and the name of the video to the video block object.
```

**Screenshots**

<img width="689" alt="Screenshot 2023-03-01 at 16 19 47" src="https://user-images.githubusercontent.com/91135600/222150510-54955dbd-fe43-425e-b0e7-85eb695ba944.png">

### Acceptance Criteria

1. Implement design as is above
1. Modal should appear over clicked video block.

Please also note:

1. If a conversation about the issue I’m working on is happening,
the outcomes should be documented within that issue (not in the comments).

**Comment by lilmithi** [comment]
Working on this

**Comment by Beulah-Matt** [comment]
Working on this.
