### ISSUE TITLE
🎨 🐛  🚀 Publish story is not working as intended

### ISSUE THREAD

**Issue by ReaganCn** [italanta/elewa#340]
**Describe the bug**
The publish story button is not saving the selected channel e.g. whatsapp, to firestore. 

**To Reproduce**
1. Go to the story you want to publish
2. Add a few blocks and save.
3. Publish story. Enter any details
4. Check document created under `channels/{theIdYouEnteredInThePreviousStep}`
5. There is no `type: "whatsapp"` field.

**Expected behavior**
When I publish the story all fields populated in the form should appear on firestore

**Screenshots**
<img width="491" alt="image" src="https://user-images.githubusercontent.com/34684844/223113709-aba783ee-6a0e-4b11-ad75-38866339de3c.png">

**Comment by marcokumu** [comment]
@ReaganCn kindly review
