### ISSUE TITLE
🎨 🚀 Enhancement of the Publish Story Form UI

### ISSUE THREAD

**Issue by ReaganCn** [italanta/elewa#341]
## User stories

As a user I should be guided when publishing a story in steps as this will simplify the process.
---

Quick links: [Summary](#summary) | [Description](#description) | [Template](#template) | [Example](#example) | [Resources](#resources)

---

### Description

The current implementation looks like this:
<img width="556" alt="image" src="https://user-images.githubusercontent.com/34684844/223121511-01c3b0e3-2053-442f-9962-8eaab0253c21.png">

As a user I should therefore be guided when publishing a story in 3 simple steps:

1.  On the first step I should select a channel - drop down
2. Depending on the channel I have chosen, I should get the relevant fields to fill. i.e. whatsapp requires phone number id and authentication key - each is a required text field
3. Lastly, I should name my bot (required), and be given the below optional fields to add:
- Message Template Name - text field 
- Template Variables - multi-select dropdown

The above is going to be implemented using an Angular Material [Stepper](https://material.angular.io/components/stepper/overview)

### Acceptance Criteria

1. I should have a multi-step form for the three different steps of publishing a story
2. The channel I select should affect the fields that i'll be given in the next steps. **The implementation for this should be there and will be tested
3. I should be able to navigate the form forwards and backwards, while the button on the last step changes to 'Publish Story'
4. After I publish the story, it should work just like the previous form.
5.  A clean design integrating the application colors.

### Resources:

* Angular Material Stepper: https://material.angular.io/components/stepper/overview
* The current modal files location:
<img width="367" alt="image" src="https://user-images.githubusercontent.com/34684844/223123751-ce0f8100-a82f-47a9-a986-18459bcbb7a5.png">

### Notes

* The design has been omitted intentionally to test your ability of identifying the current theme colors and style.
* No firestore integration should be done as it is already implemented. Just UI.

**Comment by royokite** [comment]
Working on this.
