### ISSUE TITLE
🔚 Move end block to block list

### ISSUE THREAD

**Issue by njoroge-jane** [italanta/elewa#355]
---

Quick links: [Summary](#summary) | [Description](#description) | [Template](#template) | [Example](#example) | [Resources](#resources)

---

### Summary

As a user of the CLM bot, I want the end block to be moved to the block list so that I can easily find it and use it when building conversational flows.

### Description

Currently, the end block for the CLM appears in the bot editor frame. This can make it confusing for users who are trying to build conversational flows with the bot. It would be helpful if the end block could be moved to the block list.

Moving the end block to the block list will make it easier for users to find and use when building conversational flows. It will also improve the overall user experience for the bot.

### Template

```markdown

### Acceptance Criteria

1. If I open the active bot workspace in the CLM.
1. The end block is moved from the bot editor frame to the block list.
1. The end block is clearly labeled as the end block.
1. The end block is easily accessible from the block list.
1. The user is able to use the end block to successfully end a conversation flow.
1. The functionality of the end block remains the same. 


### Resources:

* CLM Code Base: [GitHub repository for the conversational learning manager](https://github.com/italanta/elewa) ;

### [Notes]

Please also note:

If a conversation about the issue I’m working on is happening,
the outcomes should be documented within that issue (not in the comments).



```

#### * Once someone picks up this issue, they should provide an update at least every 3 days to ensure that assistance can be provided if necessary.

**Comment by Beulah-Matt** [comment]
Working on this
