### ISSUE TITLE
🎨  Redesign of the bots overview page

### ISSUE THREAD

**Issue by jrosseel** [italanta/elewa#362]
## Problem statement

In a real-life scenario, a course will typically have many different stories which each link to each other. With the current implementation this makes management and understanding of the application flow difficult for another person (who did not develop the original course) to understand.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/3729474/225562860-85745e90-0a29-4358-8f82-0123c589900a.png">
_Current bots overview page_

## Solution & Implementation

A redesign is required that allows a user to more easily understand this flow. We should easily notice:

- [ ] #364
- [ ] #363

Other desired optimalisations:
- [ ] Remove image from bot-list-item

---

**Comment by pauleen123** [comment]
working on this

**Comment by ReaganCn** [comment]
Done from JIRA
