### ISSUE TITLE
:floppy_disk: :email: Save Email Input Block Result As a Variable

### ISSUE THREAD

**Issue by LemmyMwaura** [italanta/elewa#394]
## User stories

As a user/org, I want to be able to save my users' responses when they're prompted for their email as a variable. I should also be able to validate their response to ensure it matches my expectations.

---
### Summary

Process user responses on the email input block as a variable, select the variable type, add unique validation and add a validation message that will be shown to the user if it doesn't match.

### Description:
At the moment variables as saved within their respective blocks, This also includes their `type`, `unique validation` and their `validation message`. The requirement to satisfy this issue is to continue on the same for the email Input Block.

To achieve this you will need to do the following:
- Add nested form groups for the variable and the validation fields to the form group used in the creation of the Email Input block.
- Set a checkbox in the Email Input Edit field that will be used to set validation to either True or False.
- Pass Email Block's FormGroup to the reusable variable Input component.
- Set and manage the processing of the email Input variable validation fields in their own reusable component. 

### Resources
Check how this has been done on the name Block. Implementation should be similar.
Only one validation field is required for this block at the moment: `A regex field`

The reusable component responsible for processing Inputs can be found here: `libs\features\convs-mgr\stories\blocks\process-inputs\src\lib\components\variable-input\variable-input.component.html`

The expected design for the email Input Block is shown below. (minus the max and min fields)

![Name Block validation](https://user-images.githubusercontent.com/20738858/229461459-ae9bd2d0-b0eb-4644-91df-c9a7dbaf65e4.png)

### Acceptance Criteria
1. A clean UI that makes it easy to set and update variables and changes reflected in the DB
2. Variables are saved in the block.

Please also note:
2. If a conversation about the issue I’m working on is happening,
the outcomes should be documented within that issue (not in the comments).

**Comment by SnowJunior** [comment]
Working on this
