### ISSUE TITLE
🐛 🔗 Connection Bug: Deleting block with connections

### ISSUE THREAD

**Issue by njoroge-jane** [italanta/elewa#424]
**Describe the bug**

When deleting an unsaved block in the CLM editor, the connections seem to be grouping together in a strange way, resulting in a cluttered and unclear connection.

**To Reproduce**
Steps to reproduce the behaviour:
1. Log in to CLM
2. Navigate to the content block you want to delete
3. Click on the "Delete" button for that block
4. Notice that while the unsaved block is deleted, the connections of that block do not disappear, and instead seem to be grouped together in an unexpected way, resulting in a cluttered and unclear connection.

**Expected behaviour**
The deletion of a block should also delete or remove its connections whether it's saved in the database or not. To achieve this we'll have to remove our deleted connections from the state layer and not the database.

**Screenshots**
N/A

**Desktop**
- OS: Windows 10
- Browser: Google Chrome Version 90.0.4430.93 (Official Build) (64-bit)
- Version: CLM v2.3.1

**Smartphone**
N/A

**Additional context**
How the flow works currently is when a block and connection is created then saved the deletion of the block triggers the deletion of its connections. 

**Note**:
**When a saved block is deleted the connections clutter for a second then they are deleted and therefore no more clutter.
A better solution to handle this behaviour should be considered.**

**Comment by Beulah-Matt** [comment]
Working on this.
