### ISSUE TITLE
:lipstick: :computer: Increase Side Screen Size

### ISSUE THREAD

**Issue by LemmyMwaura** [italanta/elewa#450]
## User stories

As a user/org, I want to have more room to edit my blocks.

---
### Summary

Provide more room to edit my blocks. 

### Description:
At the moment the story editor page is split between the blocks library/edit forms portal and the main editor page. To achieve this all we have to do is make is make the side screen section toggleable. We'll do that by adding a button to our main editor page that will close and open the contents on side screen for us. When the edit btn on a block is clicked while its closed it will open the side screen section but show the edit forms instead of the blocks library.

The direction of the arrow in the button should switch depending on the direction of the side screen state

## Screenshot
![SideScreen edit](https://user-images.githubusercontent.com/20738858/236168029-aa8b0178-347a-4971-9eb8-c37fd46b1d97.png)

### Acceptance Criteria

1. The Side screen section is toggleable. 

Please also note:
2. If a conversation about the issue I’m working on is happening,
the outcomes should be documented within that issue (not in the comments).

**Comment by SnowJunior** [comment]
Working on this

**Comment by Michael-Otieno** [comment]
working on this
