### ISSUE TITLE
🐛 🔍 When I search for an item I should only see relevant results

### ISSUE THREAD

**Issue by lkisenga** [italanta/elewa#466]
**Technology and Knowledge Scope 🧠**

- [x] HTML, SCSS
- [x] Typescript

**Describe the bug**
When I search for a specific item, the unrelated blocks are listed as well not just what I'm looking for. 

**To Reproduce**
1. Go to a story overview page.
2. Click on the search bar and type a search term e.g image
4. See error.

**Expected behavior**
When I search for an element, I should only see results related to that specific search and not the unrelated blocks.

**Screenshots**
![search bug](https://github.com/italanta/elewa/assets/131851875/51fcb5f4-e39d-4ab1-b630-915a962b3201)

**Comment by Allan-Ngugi** [comment]
Working on this.

**Comment by Michael-Otieno** [comment]
Working on this
