### ISSUE TITLE
🔍  Add search icon to search bar and adjust width to match margins of the blocks below it

### ISSUE THREAD

**Issue by lkisenga** [italanta/elewa#467]
## Technologies and Knowledge Scope 🧠

- [x] HTML, SCSS

---

### Description

Currently the search shows as an "S" rather than indicating a search icon which would make it more intuitive. Also, the width of the search tab doesn't match the margins of the blocks below it, thus it looks off.

![search adjustments](https://github.com/italanta/elewa/assets/131851875/88d16955-7888-4c18-8976-138fca724d3a)

### Acceptance Criteria

1. Search bar matches the width of the blocks.
1. Search icon added to the search bar.

**Comment by omaomach** [comment]
I will doing this issue

**Comment by Dx901** [comment]
Working on this
