### ISSUE TITLE
🎨 📹 Show spinner on video modal when video is uploading 

### ISSUE THREAD

**Issue by lkisenga** [italanta/elewa#478]
## Technologies and Knowledge Scope 🧠

- [x] HTML, SCSS
- [x] Typescript
- [x] Nx

## User stories

As a learning designer, when I select a video to upload I want to know that it is uploading so that I don't keep trying to upload again.
---

Quick links: [Summary](#summary) | [Description](#description) | [Template](#template) | [Example](#example) | [Resources](#resources)

---

### Description

Currently, when I select a video to upload, I cannot tell whether it is uploading or has failed, so I keep trying to select the video until it appears in the modal. When I select the video to upload, I should see a spinner that indicates the upload is in progress.

![Capturee](https://github.com/italanta/elewa/assets/131851875/11da81b9-9c11-4d58-8dec-ab4e2a6330f4)

### Acceptance Criteria

1. When I select the video and click "open"(Windows PC) a spinner appears in the video upload box indicating the upload is in progress.

**Comment by Michael-Otieno** [comment]
Working on this

**Comment by LemmyMwaura** [comment]
Completed
