### ISSUE TITLE
🎨 ❌ Prompt user of failed login attempt

### ISSUE THREAD

**Issue by lkisenga** [italanta/elewa#481]
## Technologies and Knowledge Scope 🧠

Please delete options that are not relevant.

- [x] RxJs (maybe)
- [x] HTML, SCSS
- [x] Typescript

## User stories

As I user I need to know when the login credentials I entered are wrong, so that I can correct them and try again.

---

### Description

As I user I need to know when my login attempt has failed due to wrong credentials being entered so I can regroup and try again. Currently, there is no way of knowing why I'm not able to log in. Thus, I need to see a dialog box that notifies me that either my email or password is incorrect.

![Captureee](https://github.com/italanta/elewa/assets/131851875/a7820c32-7bee-4c5e-a800-f21d278aca9e)

### Acceptance Criteria

1. When the user clicks "proceed" and the wrong credentials have been entered, a dialog box should notify them that either the email or password is incorrect.
2. When user tries to login again, the dialog box should disappear.

### Notes

This depends on #480

**Comment by Allan-Ngugi** [comment]
Working on this.
