### ISSUE TITLE
🎨 🔲 Add an upload button to video block modal

### ISSUE THREAD

**Issue by lkisenga** [italanta/elewa#482]
## Technologies and Knowledge Scope 🧠

- [x] RxJs
- [x] HTML, SCSS
- [x] Typescript

## User stories

As a content designer I should be able to easily know where to click in order to upload/ change a video in the video modal. 

### Description

As a content designer I should be able to easily know where to click in order to upload/ change a video in the video modal. 

Currently, when I open the video modal I have to click inside the box beneath the name in order to upload a video. This is not intuitive. Adding a separate upload button makes it easier to know where to click in order to upload the video.

![MicrosoftTeams-image (1)](https://github.com/italanta/elewa/assets/131851875/58885fbe-7fcd-4847-83b3-043f848def8f)

### Acceptance Criteria

1. When the edit button is clicked on the video block, the video modal pops up.
2. The upload button should be clearly visible within the modal.
3. Clicking the upload button should open a folder from which I can navigate to the video I want.

### Notes

This should be available for both the initial upload and edits.

**Comment by kangzy-fix** [comment]
Working on this.
