### ISSUE TITLE
🎨 ✏️ Edit button from the video should take you back to the modal when clicked

### ISSUE THREAD

**Issue by lkisenga** [italanta/elewa#483]
## Technologies and Knowledge Scope 🧠

- [x] RxJs
- [x] HTML, SCSS
- [x] Typescript

## User stories

As a user, I may want to change the video or name of the video in the video block. Thus, when I click the "edit" button on the video block, the modal should pop up again so I can make the changes I want to.

---

### Description
As a user, I may want to change certain details in the video block after the video has been uploaded. Thus the modal should pop up allowing me to make these changes. 

Currently, when I click the edit button on the video block, it opens a side panel that doesn't allow me to edit the video.

![image](https://github.com/italanta/elewa/assets/131851875/de537a52-a890-4e08-ba4b-039842298d24)

What should happen is that when I click "edit" the modal should pop up again and show the current video within it so I can make the changes I wish to whether changing the name or uploading a different video.

![image](https://github.com/italanta/elewa/assets/131851875/40b586ab-2936-4263-9d58-0855c0ac3f67)

### Acceptance Criteria

1. When I click "edit" the modal pops up.
2. Within the modal I should see the name, and the video should be visible within the video box.
3. I should be able to edit the name, and upload a new video.

**Comment by jeffoty** [comment]
working on this.
