### ISSUE TITLE
🎨 🔲 Change jump block drop down menu into text field

### ISSUE THREAD

**Issue by lkisenga** [italanta/elewa#501]
## Technologies and Knowledge Scope 🧠
- [x] HTML, SCSS

### User Stories
As a user, I should be able to paste the block ID into the jump block after copying it from the relevant block.

### Description

Currently the jump block requires the user to select the ID of the block to jump to from a drop-down menu. In order to be able to paste the block ID into the jump block, this field needs to be converted from a drop-down menu to a text field.

![image](https://github.com/italanta/elewa/assets/131851875/36ce8c84-6024-43d0-aefe-fa9d7ccf21e1)

### Acceptance Criteria

1. If I click into the field I should be able to type/paste a number within it.

### Notes

Related to #500, but not dependent.

**Comment by Allan-Ngugi** [comment]
Working on this.

**Comment by order6677** [comment]
working on this
