### ISSUE TITLE
⚠️ Throw error warning if the flow has errors

### ISSUE THREAD

**Issue by EvalyneG** [italanta/elewa#514]
**User Story**

As a user, when I am saving my story, I want to receive clear and informative notifications if there is error(s) in my flow, so that I can quickly identify the cause of the issue and take necessary steps to resolve the issue(s)

**Screenshot**
![Capture](https://github.com/italanta/elewa/assets/131855290/8ff21b0f-4c22-4c77-a16b-4ab5365187b1)

**Acceptance Criteria**
1. The error message(s) should appear next to the save option
2. An error message should have the following: error heading, description of the error as a link - when clicked on it should lead to the block with the error, error icon and a cancel icon as shown on the design.
3. Clicking on the error information (the underlined information) should directly navigate to the exact block where the issue is. 
4. When multiple errors occur, a maximum of two errors should be displayed at a time. Clicking on the cancel icon should close the selected issue, and the next issue should appear first and the next issue should appear second.

**Comment by paulkahura** [comment]
Fixed by #607
