### ISSUE TITLE
🎨 📈 📜 Improvement on the Assessment List Page

### ISSUE THREAD

**Issue by ReaganCn** [italanta/elewa#533]
## Technologies and Knowledge Scope 🧠

Please delete options that are not relevant.

- [ ] HTML, SCSS
- [ ] Typescript

## User stories

This is the current design:
<img width="1668" alt="image" src="https://github.com/italanta/elewa/assets/34684844/d9a90ebc-268d-48e7-b5d2-0f649e22f573">

This is how it should be: 

![MicrosoftTeams-image (4)](https://github.com/italanta/elewa/assets/34684844/e5071360-ab53-42cd-9561-460dc32f126d)

---

Quick links: [Summary](#summary) | [Description](#description) | [Template](#template) | [Example](#example) | [Resources](#resources)

---

### Description

Apart from the design matching, the assessment title shown is a hyperlink and when a user clicks it, it should take them to the assessment page to view it. This functionality already exists and should just be transferred from the "View" Button.

A pointer cursor should be shown when I hover over an assessment title.

### Acceptance Criteria

1. The design should be pixel perfect
2. I should be taken to the specific assessment page when I click on the assessment title.
3. Match the roundness of the buttons in the design

**Comment by Beulah-Matt** [comment]
Working on this
