### ISSUE TITLE
🎨  Update main side panel menu items

### ISSUE THREAD

**Issue by EvalyneG** [italanta/elewa#549]
## Description
The main side-panel menu items need to be updated

The following changes are required:
1. Update 'Dashboard' to 'Bots' and add 'Active Bots' as a submenu.
2. Add 'Analytics' as a new menu item, and include 'Dashboard' and 'Reports' as submenus under it.
3. Add 'Learners' as a new menu item in the main side panel menu.
4. Replace the current assessments icon with the updated one shown in the new design.
5. Ensure that the icons for 'Bots', 'Analytics' and 'Learners' match the ones depicted in the new design.

### Existing Design
<img width="239" alt="Screenshot 2023-07-05 at 15 51 48" src="https://github.com/italanta/elewa/assets/131855290/1a0834ff-bbb1-4d9d-9803-7f4deb3f1b05">

### New Design
<img width="350" alt="Screenshot 2023-07-05 at 15 51 19" src="https://github.com/italanta/elewa/assets/131855290/ff43900b-5d12-40b4-89e1-3be6ea085339">

**Comment by Beulah-Matt** [comment]
Working on this
