### ISSUE TITLE
:lipstick:  Audio Block Redesign: block redesign

### ISSUE THREAD

**Issue by paulkahura** [italanta/elewa#641]
## User stories

As a user, I want the "Audio Block" component in the app to be redesigned to enhance its usability and visual appeal.

---

Quick links: [Summary](#summary) | [Description](#description) | [Template](#template) | [Example](#example) | [Resources](#resources)

---

### Technical Description
The current design is: 
![image](https://github.com/italanta/elewa/assets/35740939/0af5830b-37e4-4c6b-b98d-1bb122f1ebea)

It should be changed to:
![Audio Block](https://github.com/italanta/elewa/assets/20738858/2cdca764-0636-4d29-8da3-decd7bad098d)

The files can be found at `libs/features/convs-mgr/stories/blocks/library/audio-message-block/`. 
NB: The wave should be formed from the audio uploaded by the user. 

The designs are [here](https://www.figma.com/file/ZGHzSstXOYPMFU1EiqjEHD/Block-redesigns?type=design&node-id=0%3A1&mode=design&t=3Un6MsnHbMNrPCaD-1)

### Acceptance Criteria

1. The block should look exactly like the designs.
2. Use of `rem`, `em` as opposed to `px`.
3. All changes should be isolated to the following  `libs/features/convs-mgr/stories/blocks/library/audio-message-block/`.

**Comment by LemmyMwaura** [comment]
@ndush and anyone else working on this, kindly take note of the updated design spec.
