### ISSUE TITLE
:lipstick:  :art:  Audio Input Block Redesign: block redesign

### ISSUE THREAD

**Issue by paulkahura** [italanta/elewa#642]
## User stories

As a user, I want the "Audio Input Block" component in the app to be redesigned to enhance its usability and visual appeal.

---

Quick links: [Summary](#summary) | [Description](#description) | [Template](#template) | [Example](#example) | [Resources](#resources)

---

### Technical Description
The current design is: 
![image](https://github.com/italanta/elewa/assets/35740939/4f5e6be7-0b78-4a3e-a472-bbb98da0fb07)

It should be changed to:
![image](https://github.com/italanta/elewa/assets/35740939/c776a2dc-1a56-4621-8e9e-a78cb926d4ef)

The files can be found at `libs/features/convs-mgr/stories/blocks/library/audio-input-block/`. 

The designs are [here](https://www.figma.com/file/ZGHzSstXOYPMFU1EiqjEHD/Untitled?type=design&node-id=1%3A4&mode=design&t=Hf7DxaUUMQ3BWy57-1)

### Acceptance Criteria

1. The block should look exactly like the designs.
2. Use of `rem`, `em` as opposed to `px`.
3. All changes should be isolated to the following  `libs/features/convs-mgr/stories/blocks/library/audio-input-block/`.

**Comment by LemmyMwaura** [comment]
Closing this as the desired implementation is wrong for an input block.
