### ISSUE TITLE
🎨 Add a "Create bot" option if user has no bots yet

### ISSUE THREAD

**Issue by jrosseel** [italanta/elewa#72]
## User stories

A user story is implemented as well as it is communicated.
If the context and the goals are made clear, it will be easier for everyone to implement it, test it, refer to it…

---

Quick links: [Summary](#summary) | [Description](#description) | [Template](#template) | [Example](#example) | [Resources](#resources)

---

### Summary

On the user home page (bot dashboard), the page currently looks empty when no bots are created yet. As depicted below:

<img width="1420" alt="image" src="https://user-images.githubusercontent.com/3729474/192232569-e11222fb-db49-476b-bf5e-aeac437700b1.png">

To increase my user experience, as a user I'd like to be guided by a larger and more inviting card in case I have no bots, as depicted below:

<img width="986" alt="image" src="https://user-images.githubusercontent.com/3729474/192233914-f1549cf4-4539-4682-b3ca-827c3018de6c.png">

**Comment by kelvinmburu** [comment]
Hello, kindly assign me this issue so I can work on it

**Comment by kenyansa** [comment]
I'll give it a try too.
