### ISSUE TITLE
:art:  Remove full stop and Org dropdown

### ISSUE THREAD

**Issue by paulkahura** [italanta/elewa#743]
As a user i want just one fullstop at the end of the line.

![image-20231019-064415](https://github.com/italanta/elewa/assets/35740939/3b5a79ed-9c3d-4608-9e09-1988e5992354)

files are here: `libs/features/app/auth/login/src/lib/components/login`

What is this postal code drop-down for? I couldn’t use it to enter my postal code. I think we should do away with it, and have users enter it manually. Alternatively, the drop down could include a list of regions/areas with their respective area/postal codes

![image-20231019-070359(1)](https://github.com/italanta/elewa/assets/35740939/1d04d956-ff7d-4186-b8e9-95271bb45236)

files are here: `libs/private/features/convs-mgr/orgs/src/lib/pages/orgs-pages`

**Comment by LemmyMwaura** [comment]
Assigned to @Mutagah
