### ISSUE TITLE
:art:  Sign up design changes

### ISSUE THREAD

**Issue by paulkahura** [italanta/elewa#745]
Change wording of 7 day trial to: Sign up to create a world of engaging learning experiences

Increase spacing between the logo and Create an Account wording

Start your 7 Day trial part to have a lighter font weight

Reduce spacing of the Log In wording – move it closer to already have an account? Have the font weight be uniform - go with the Log In font weight

Log in link to highlight on hover

files are here: `libs/features/app/auth/login/src/lib/components/register`

**Comment by LemmyMwaura** [comment]
Assigned to @Mutagah
