### ISSUE TITLE
🎨💄 CLM-322Collapse Chats and Templates sub-menu into Messaging

### ISSUE THREAD

**Issue by JAPHETHNYARANGA** [italanta/elewa#787]
### User Stories

The Messaging menu is not clickable at the moment. Also, the Chats and Message Templates appear out of alignment when the menu is collapsed. 
We should therefore nest them under Messaging, and then when this is clicked the menu opens and the two are visible. 

###Technical Description 
The page currently has this design
### Current design

![Screenshot from 2023-11-01 08-44-12](https://github.com/italanta/elewa/assets/71229825/ffc80627-fc59-4de5-848e-f5e0b715a4d9)

## Assets
![angle-small-down](https://github.com/italanta/elewa/assets/20738858/704bee2b-b0e5-4b8a-8335-f7c82899db87)

it should be changed to this design
### Required design

![image-20231031-115905](https://github.com/italanta/elewa/assets/71229825/f7d6c33c-bb37-4b00-97f2-33fe938ad1cd)

The file to edit is in this  path `libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.html`
### Acceptance Criteria

1.The default behaviour of the menu should be that Chats and Message Templates are nested under the Messaging parent. 

2.When the user clicks on Messaging the menu should open and Chats and Message Templates are then visible so the user can navigate wherever they wish.
3.Do not change the icons. Only add the drop down.

**Comment by LemmyMwaura** [comment]
I've added the asset as a PNG @Mutagah @thadeusdev @dennis-mburu

**Comment by Mutagah** [comment]
> I've added the asset as a PNG @Mutagah @thadeusdev @dennis-mburu

Unable to locate the provided PNG, could you please specify the path?

**Comment by LemmyMwaura** [comment]
> > I've added the asset as a PNG @Mutagah @thadeusdev @dennis-mburu
> 
> Unable to locate the provided PNG, could you please specify the path?

My bad. Hadn't saved. Should be visible now
