### ISSUE TITLE
🎨💄 CLM-326-Change button text to "edit"

### ISSUE THREAD

**Issue by JAPHETHNYARANGA** [italanta/elewa#788]
### User Stories

Description

There is too much text within this button that makes it wrap around on some screens. Change the text to simply read “edit”.

###Technical Description 
The page currently has this design
### Current design

![image-20231031-113639](https://github.com/italanta/elewa/assets/71229825/ed86516d-03fc-40b1-bfbb-7803ba44bf0b)

For this issue, you just need to edit the languages file for both french and english from "Edit company information" to "Edit".
You can use google translator
path to files fr- `apps/conv-learning-manager/src/assets/i18n/fr.json`
en- `apps/conv-learning-manager/src/assets/i18n/en.json`
### Acceptance Criteria

1.Text in the button should read “Edit” and not “Edit Company Information”.

**Comment by WendyNjuguna** [comment]
working on this
