### ISSUE TITLE
🎨 [Application design] Add user menu and configuration to the app bar

### ISSUE THREAD

**Issue by jrosseel** [italanta/elewa#8]
## User stories

As part of the initial application design, which can be viewed [here](link-to-xd), a user menu where the user can manage his/her information and configuration is key to the basic user journey on the platform.

---

Quick links: [Summary](#summary) | [Description](#description) | [Technical Analysis](#technical-analysis) | [Resources](#resources)

---

### Summary

We cover the following user stories :

As a **user**, I want to **access my information to review and manage my information** at **any time in my user journey** through a **visible user menu**.

As a **user**, I want to be able to **log out of the platform** at **any time in my user journey** through a **visible user menu**.

### Description

At this point, we are only covering the basic cases of the user menu. 

The user menu is designed as follows: 
<img width="239" alt="image" src="https://user-images.githubusercontent.com/3729474/180762382-43b7082a-34a8-4ccc-a937-b55449f7063e.png">

It is placed in the top right corner of the top menu bar.

--
When hovering, background colour changes to **'#fafafa'**. The button's border-radius of 5 pixels should clearly be shown.

When clicked :
```markdown
1. I click on user menu 
2. A dropdown appears which showcases the different options I have:
  2.1. Logout
```

### Technical analysis

1. The User Menu
```markdown
- The component should be called 'app-user-menu'
- It resides in project 'elements/layout/user-control' which exports the UserControlModule module, of which the component is a part. (use cmd 'nx generate @nrwl/angular:library elements/layout/user-control' to generate)
- Convl-Layout module to import UserControlModule
- 'app-user-menu' to be imported in 'convl-page'

- The design should be built on top of Angular Material.
- The button relies on mat-button
- The menu relies on mat-menu
]
```
2. The log out
```markdown
- Seperate component for the logout-button inside of the menu
- Component is called 'app-logout'
- Component uses the UserService to perform the log out.
```

### Acceptance Criteria

1. Button should be placed correctly
2. Should implement correct architectural constraints as described

### Resources:

* Mockups: [Here goes a URL to or the name of the mockup(s) in XD];

**Comment by gladyswambura** [comment]
I am working on this issue

**Comment by MachukaJoy** [comment]
Interested

**Comment by NinaWendy** [comment]
I'll take up this issue
