### ISSUE TITLE
🎨  CLM-369 Bots (Main, Modules, Lessons) Page(s) Design Cleanup

### ISSUE THREAD

**Issue by LemmyMwaura** [italanta/elewa#888]
### Main Page

1. Bots Page Title

- Set page title font-size to 2rem, font-weight to 400, and margin-top to -10px.

2. Date Created and View All functions should not have a joined background.

![Screenshot 2023-11-24 at 12 57 20](https://github.com/italanta/elewa/assets/20738858/f8a0531c-b4e4-4776-ad7d-214d9ee2b476)

3. Search Function

- Remove the white background from the search input field.

- Adjust the search icon to face the opposite direction.

- Lighten the font-weight of 'Search for a Course' (font-weight: 300).

 4. Table Row Hover Effect

- Implement a hover effect on table data with background-color: #1F7A8C and 40% opacity not as it is currently.

![Screenshot 2023-11-24 at 12 42 52](https://github.com/italanta/elewa/assets/20738858/c1052a59-c25a-4da0-858e-d7b4f31f35e9)

### Modules Page

1. Title - Module page title should have font-size: 2rem, font-weight: 400, margin-top: -10px.

2. Search function

![Screenshot 2023-11-24 at 13 00 32](https://github.com/italanta/elewa/assets/20738858/c3555fa9-b86f-44de-8691-26e9b92d1d96)

- The icon is out of the search input field

- Make the icon face the opposite direction

- Reduce the font weight to 300

3. Module card

![Screenshot 2023-11-24 at 13 03 52](https://github.com/italanta/elewa/assets/20738858/e9327fa1-dda9-498a-8dd5-1357a58c563f)

- Align the module name (in this case ‘demo module’) horizontally with the menu icon

### Lessons Page

1.  Title - Lessons page title should have font-size: 2rem, font-weight: 400, margin-top: -10px.

2. Search function

- The icon is out of the search input field

- Make the icon face the opposite direction

- Reduce the font-weight to 300

3. Lesson card

- Align the module name horizontally with the menu icon

**Comment by darlene9497** [comment]
@LemmyMwaura by this: The icon is out of the search input field, do you mean we ought to put the icon inside the search input field or leave it outside the search input field. Please clarify this. Thanks
