### ISSUE TITLE
:art: CLM-375 Settings Page Design Cleanups

### ISSUE THREAD

**Issue by LemmyMwaura** [italanta/elewa#889]
1. Title - should have font-size: 2rem, font-weight: 400, margin-top: -10px.

2. 
<img width="710" alt="Screenshot 2023-11-24 at 13 31 57" src="https://github.com/italanta/elewa/assets/20738858/14df2702-26a9-40ee-85b7-3bd8f5ed8f67">

This was the design. From the current implementation, correct the following:
- Background color
- Have a background on search function and all roles filter
- Invite member font-size to be 14px
- Let the hover background effect be of color #1F7A8C of opacity 40%

3. In the permissions tab, let the hover background effect be of color #1F7A8C of opacity 40%

![Screenshot 2023-11-24 at 13 33 26](https://github.com/italanta/elewa/assets/20738858/3eccdd99-558d-4bd3-9680-d646f94c1e35)

4. Center this part:

![Screenshot 2023-11-24 at 13 36 45](https://github.com/italanta/elewa/assets/20738858/2966667e-8c54-4d49-94a1-cf61f560d868)

**Comment by Mutagah** [comment]
@LemmyMwaura , the hover effect on the members tab does it apply to the search input and the table itself?

**Comment by LemmyMwaura** [comment]
> @LemmyMwaura , the hover effect under the members tab, does it apply to the search input and the table itself?

It applies to each row.
