### ISSUE TITLE
🎨 Single Learner Page Redesign.

### ISSUE THREAD

**Issue by LemmyMwaura** [italanta/elewa#891]
## User stories

As a user, I want a neatly designed single learner page for my enrolled users.

### Description

Redesign the single learner page to match the new design. (Only thing that should not be accounted for is the assessments section). Only the table header in that section will need to be resigned at the moment.

### Screenshot

- Current Design.
<img width="1174" alt="Screenshot 2023-12-01 at 13 34 04" src="https://github.com/italanta/elewa/assets/20738858/fa4a7601-6c46-4cef-bfb6-21e524dd19ab">

- Expected Design.

<img width="538" alt="Screenshot 2023-12-01 at 13 23 48" src="https://github.com/italanta/elewa/assets/20738858/dbfd7a0c-50ed-46aa-8b99-73c06029c7b6">

### Acceptance Criteria

1. I have clear Acceptance criteria [what a beautiful recursion].
1. I have to understand the logic of the mockups, more than the pixels used, so that we can optimize the code.

**Comment by levy-web** [comment]
@LemmyMwaura kindly provide figma access to this new design
